In [1]:
import numpy as np
import pandas as pd

In [2]:
train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

In [3]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 251.5 MB

In [4]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28000 entries, 0 to 27999
Columns: 784 entries, pixel0 to pixel783
dtypes: int64(784)
memory usage: 167.5 MB

In [5]:
ImageId = test_data.index + 1
y=train_data.iloc[:,0]
X=train_data.iloc[::,1:]
X_test=test_data

In [6]:
y

0        1
1        0
2        1
3        4
4        0
        ..
41995    0
41996    1
41997    7
41998    6
41999    9
Name: label, Length: 42000, dtype: int64

In [7]:
X

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
X_test

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
X=X/255
X_test=X_test/255

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X,y,test_size=0.1,random_state=1)
X_train.shape,X_val.shape,y_train.shape,y_val.shape,X_test.shape

((37800, 784), (4200, 784), (37800,), (4200,), (28000, 784))

In [11]:
from sklearn.neural_network import MLPClassifier
model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=50, alpha=1e-5, solver='sgd', verbose=10, random_state=1, learning_rate='constant', learning_rate_init=0.1).fit(X_train, y_train)
print(model.score(X_train, y_train))

Iteration 1, loss = 0.35716198
Iteration 2, loss = 0.15246260
Iteration 3, loss = 0.10602747
Iteration 4, loss = 0.08047528
Iteration 5, loss = 0.06477129
Iteration 6, loss = 0.05234676
Iteration 7, loss = 0.04274301
Iteration 8, loss = 0.03627914
Iteration 9, loss = 0.03097303
Iteration 10, loss = 0.02434672
Iteration 11, loss = 0.02065805
Iteration 12, loss = 0.01704809
Iteration 13, loss = 0.01414361
Iteration 14, loss = 0.01193299
Iteration 15, loss = 0.01037037
Iteration 16, loss = 0.00873767
Iteration 17, loss = 0.00705251
Iteration 18, loss = 0.00595231
Iteration 19, loss = 0.00533411
Iteration 20, loss = 0.00460985
Iteration 21, loss = 0.00407173
Iteration 22, loss = 0.00355988
Iteration 23, loss = 0.00314260
Iteration 24, loss = 0.00296507
Iteration 25, loss = 0.00281320
Iteration 26, loss = 0.00253516
Iteration 27, loss = 0.00237036
Iteration 28, loss = 0.00216156
Iteration 29, loss = 0.00203464
Iteration 30, loss = 0.00191830
Iteration 31, loss = 0.00185982
Iteration 32, loss = 0.00175328
Iteration 33, loss = 0.00167295
Iteration 34, loss = 0.00156420
Iteration 35, loss = 0.00151313
Iteration 36, loss = 0.00144417
Iteration 37, loss = 0.00138421
Iteration 38, loss = 0.00134749
Iteration 39, loss = 0.00127503
Iteration 40, loss = 0.00123198
Iteration 41, loss = 0.00118648
Iteration 42, loss = 0.00115699
Iteration 43, loss = 0.00112032
Iteration 44, loss = 0.00108025
Iteration 45, loss = 0.00104112
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
1.0

In [12]:
y_pred=model.predict(X_val)
print(model.score(X_val,y_val))

0.9716666666666667

In [13]:
df_val=pd.DataFrame({'actual_value':y_val, 'predicted_value':y_pred})
df_val.reset_index(drop=True, inplace=True)
df_val

      actual_value  predicted_value
0                1                1
1                5                5
2                2                2
3                8                8
4                4                4
...            ...              ...
4195             0                0
4196             0                0
4197             4                4
4198             0                0
4199             0                0

[4200 rows x 2 columns]

In [14]:
pred=model.predict(X_test)
pred

array([2, 0, 9, ..., 3, 9, 2], dtype=int64)

In [15]:
output = pd.DataFrame({'ImageId': ImageId, 'Label': pred})
output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!